export enum PaymentStatusEnum {
    COMPLETED='COMPLETED',
    ERROR='ERROR',
    PENDING='PENDING',
    PENDING_CHALLENGE='PENDING_CHALLENGE',
    CANCELLED='CANCELLED',
    COMPLETED_AGENT='COMPLETED_AGENT'
}